language: clojure
before_script:
  - mkdir checkouts
  - cd checkouts && git clone https://github.com/USGS-EROS/lcmap-config.git && cd -
  - cd checkouts && git clone https://github.com/USGS-EROS/lcmap-client-clj.git && cd -
  - cd checkouts && git clone https://github.com/USGS-EROS/lcmap-data.git && cd -
  - cd checkouts && git clone https://github.com/USGS-EROS/lcmap-see.git && cd -
  - cd checkouts && git clone https://github.com/USGS-EROS/lcmap-event.git && cd -
script:
  - make check
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk6
  - openjdk7
  #- openjdk8
#addons:
#  apt:
#    sources:
#      - 
