sudo: required
dist: trusty
language: clojure
before_install:
  - sudo apt-add-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libgdal-dev libgdal-java -y
before_script: test/support/setup.sh
script:
  - make check
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk6
  #- openjdk7
  - openjdk8
#addons:
#  apt:
#    sources:
#      -
notifications:
  email:
      # the following won't work until the Travis
      # but here is sorted:
      # https://github.com/travis-ci/travis-ci/issues/2513
      - lcmap-dev-notifications@googlegroups.com
      - duncan.mcgreggor.ctr@usgs.gov
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#rest
